from pathlib import Path
p=Path('src/app/dashboard/canvas/editor/page.tsx')
s=p.read_text()
old='''      canvas.on("object:scaling", (e: any) => {\n        const obj = e.target;\n        if (!obj) return;\n        if (obj.type === "textbox" || obj.type === "i-text") {\n          const newSize = Math.round(obj.fontSize * obj.scaleY);\n          setSelFontSize(newSize);\n        }\n        if (obj.type === "rect") {\n          const storedRx = rectBeforeScale.current?.rx ?? (obj.rx || 0);\n          const sx = obj.scaleX || 1;\n          const sy = obj.scaleY || 1;\n          const newW = obj.width * sx;\n          const newH = obj.height * sy;\n          const maxRx = Math.min(newW, newH) / 2;\n          const newRx = Math.min(storedRx, maxRx);\n          obj.set({ width: newW, height: newH, rx: newRx, ry: newRx, scaleX: 1, scaleY: 1 });\n          rectBeforeScale.current = { rx: newRx, ry: newRx };\n          obj.setCoords();\n        }\n      });'''
new='''      canvas.on("object:scaling", (e: any) => {\n        const obj = e.target;\n        if (!obj) return;\n        // Do not rewrite dimensions while Fabric owns an active corner transform.\n        if (obj.type === "textbox" || obj.type === "i-text") {\n          const newSize = Math.round(obj.fontSize * Math.abs(obj.scaleY || 1));\n          setSelFontSize(newSize);\n        }\n      });'''
assert old in s
s=s.replace(old,new,1)
old='''        if (obj.type === "rect") {\n          rectBeforeScale.current = { rx: obj.rx || 0, ry: obj.ry || 0 };\n          canvas.requestRenderAll();\n          syncSel(obj);\n        }\n      });'''
new='''        if (obj.type === "rect") rectBeforeScale.current = { rx: obj.rx || 0, ry: obj.ry || 0 };\n        obj.setCoords?.();\n        if (obj.__threeD?.enabled) refreshThreeDObject(obj);\n        canvas.requestRenderAll();\n        syncSel(obj);\n      });'''
assert old in s
s=s.replace(old,new,1)
start=s.index('      canvas.on("mouse:down", (e: any) => {\n        // Robust selection fallback.')
end=s.index('\n\n        if (isEditingNodesRef.current && editingData.current) {',start)
replacement='''      canvas.on("mouse:down", (e: any) => {\n        if (activeToolRef.current === "select" && !isEditingNodesRef.current && !(canvas as any)._currentTransform) {\n          const pointer = canvas.getPointer(e.e);\n          const objects = canvas.getObjects().filter((o:any) => o && o.visible !== false && o.selectable !== false && o.evented !== false && !o.isControlHelper && !o.isEditPreview);\n          let preferredPath:any = null;\n          for (let i = objects.length - 1; i >= 0; i--) {\n            const o = objects[i];\n            if (o.type !== "path") continue;\n            try {\n              o.setCoords?.();\n              const br = o.getBoundingRect(true, true);\n              const d3Pad = o.__threeD?.enabled ? Math.min(36, 10 + Number(o.__threeD?.depth || 0) * 0.12) : 0;\n              const pad = Math.max(12, Number(o.strokeWidth || 0) * 2 + 6, d3Pad);\n              if (pointer.x >= br.left - pad && pointer.x <= br.left + br.width + pad && pointer.y >= br.top - pad && pointer.y <= br.top + br.height + pad) { preferredPath = o; break; }\n            } catch {}\n          }\n          if (preferredPath && preferredPath !== e.target) {\n            preferredPath.set({ selectable:true, evented:true, hasControls:true, hasBorders:true });\n            preferredPath.setCoords?.();\n            canvas.setActiveObject(preferredPath);\n            syncSel(preferredPath);\n            canvas.requestRenderAll();\n          } else if (!e.target) {\n            for (let i = objects.length - 1; i >= 0; i--) {\n              const o = objects[i];\n              try {\n                o.setCoords?.(); const br = o.getBoundingRect(true, true); const pad = o.__threeD?.enabled ? 10 : 4;\n                if (pointer.x >= br.left-pad && pointer.x <= br.left+br.width+pad && pointer.y >= br.top-pad && pointer.y <= br.top+br.height+pad) { canvas.setActiveObject(o); syncSel(o); canvas.requestRenderAll(); break; }\n              } catch {}\n            }\n          }\n        }'''
s=s[:start]+replacement+s[end:]
old='''    newPath.__uid = originalPathObj.__uid;\n\n    const idx = canvas.getObjects().indexOf(originalPathObj);'''
new='''    newPath.__uid = originalPathObj.__uid;\n    newPath.set({ selectable:true, evented:true, hasControls:true, hasBorders:true, padding: Math.max(Number(originalPathObj.padding || 0), 8) });\n    newPath.setCoords();\n\n    const idx = canvas.getObjects().indexOf(originalPathObj);'''
assert old in s
s=s.replace(old,new,1)
p.write_text(s)
