from pathlib import Path

p = Path('src/app/dashboard/canvas/editor/page.tsx')
s = p.read_text()

old = '''  const applyVectorBlurRendering = (obj: any, value: number) => {\n    if (!obj || obj.type === "image") return;\n    obj.__vectorBlur = Math.max(0, value || 0);\n    if (!obj.__vectorBlurOriginalRender) {\n      obj.__vectorBlurOriginalRender = obj._render;\n      obj._render = function(ctx: CanvasRenderingContext2D) {\n        ctx.save();\n        const blurValue = Math.max(0, this.__vectorBlur || 0);\n        if (blurValue > 0) ctx.filter = `blur(${Math.max(0.25, blurValue * 0.3)}px)`;\n        this.__vectorBlurOriginalRender.call(this, ctx);\n        ctx.restore();\n      };\n    }\n    obj.set({ padding: obj.__vectorBlur > 0 ? Math.ceil(obj.__vectorBlur * 1.2) : 0 });\n    obj.dirty = true;\n  };'''
new = '''  const applyVectorBlurRendering = (obj: any, value: number) => {\n    if (!obj) return;\n    const blurValue = Math.max(0, value || 0);\n    obj.__vectorBlur = blurValue;\n\n    if (obj.__blurOriginalObjectCaching === undefined) {\n      obj.__blurOriginalObjectCaching = obj.objectCaching !== false;\n    }\n\n    if (!obj.__vectorBlurOriginalRender) {\n      obj.__vectorBlurOriginalRender = obj._render;\n      obj._render = function(ctx: CanvasRenderingContext2D) {\n        ctx.save();\n        const v = Math.max(0, Number(this.__vectorBlur || 0));\n        if (v > 0) {\n          // Apply blur to the fully rendered object, not to its source pixels.\n          // This lets the blur bleed outside vector and image bounds instead of\n          // being clipped to Fabric's object/image cache rectangle.\n          ctx.filter = `blur(${Math.max(0.5, v * 0.35)}px)`;\n        }\n        this.__vectorBlurOriginalRender.call(this, ctx);\n        ctx.restore();\n      };\n    }\n\n    // Fabric object caching clips filter pixels to the cache bounds. Disable it\n    // while blur is enabled so soft edges can extend naturally past the object.\n    obj.set({\n      objectCaching: blurValue > 0 ? false : !!obj.__blurOriginalObjectCaching,\n      padding: blurValue > 0 ? Math.ceil(blurValue * 1.8) : 0,\n    });\n    obj.dirty = true;\n    obj.setCoords?.();\n  };'''
assert old in s, 'applyVectorBlurRendering marker missing'
s = s.replace(old, new, 1)

old = '''  const copyBlurMetadata = (source: any, target: any) => {\n    if (!source || !target) return;\n    const blur = source.__vectorBlur ?? (source.__uid ? blurValueMap.current.get(source.__uid) : 0) ?? 0;\n    if (target.type !== "image" && blur > 0) {\n      target.__vectorBlur = blur;\n      applyVectorBlurRendering(target, blur);\n    }\n  };'''
new = '''  const copyBlurMetadata = (source: any, target: any) => {\n    if (!source || !target) return;\n    const blur = source.__vectorBlur ?? (source.__uid ? blurValueMap.current.get(source.__uid) : 0) ?? 0;\n    if (blur > 0) {\n      target.__vectorBlur = blur;\n      applyVectorBlurRendering(target, blur);\n    }\n  };'''
assert old in s, 'copyBlurMetadata marker missing'
s = s.replace(old, new, 1)

old = '''    if (sel.type === "image") {\n      const fabric = (window as any).fabric;\n      const filters = (sel.filters || []).filter((f: any) => f.type !== "Blur");\n      if (v > 0) filters.push(new fabric.Image.filters.Blur({ blur: v / 100 }));\n      sel.filters = filters;\n      sel.set({ padding: v > 0 ? Math.round(v * 0.8) : 0 });\n      sel.applyFilters();\n      sel.dirty = true;\n      fc.current.requestRenderAll();\n      return;\n    }\n\n    // Vector/text objects remain true Fabric objects. Blur is applied only at render time,\n    // so copy/paste, node editing, fills and strokes remain fully editable.\n    applyVectorBlurRendering(sel, v);\n    fc.current.requestRenderAll();'''
new = '''    if (sel.type === "image") {\n      // Remove the old Fabric source-pixel Blur filter. It is constrained to the\n      // image rectangle and therefore leaves a hard outer edge. Other image\n      // adjustment filters remain intact.\n      const filters = (sel.filters || []).filter((f: any) => f.type !== "Blur");\n      if (filters.length !== (sel.filters || []).length) {\n        sel.filters = filters;\n        sel.applyFilters();\n      }\n    }\n\n    // Use the same post-render blur for vectors, text and images. This preserves\n    // editability and lets the blur extend beyond the object's visible bounds.\n    applyVectorBlurRendering(sel, v);\n    fc.current.requestRenderAll();'''
assert old in s, 'updateBlur marker missing'
s = s.replace(old, new, 1)

p.write_text(s)
